# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_h9IdlKiqWfafYzCF7oRKU5auJdR-PNv
"""

import streamlit as st


st.write('''
#App for Substracting 2 Numbers
''')

#Get input

st.header('Number input:')

def user_input_features():
  first_num = st.number_input('FIRST_NUMBER')
  second_num = st.number_input('SECOND_NUMBER')

data = {
    'FIRST_NUMBER':first_num,
    'SECOND_NUMBER':second_num
}

st.write(f'The result of substracting {first_num} from {second_num} is: {first_num-SECOND_NUMBER}')